version: "2"

services:
  logregator:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: logs
    volumes:
      - "logdata:/data"
    env_file:
      - ./env.txt
    ports:
      - "12201:12201/udp"
      - "8080:8080"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

volumes:
  logdata:

      